name: My CI/CD Pipeline

on:
  push:
     branches:
       - main

jobs:
  run-first-job:
    runs-on: ubuntu-latest

    steps:
         - name: Step 1 - Start message
           run: echo "Starting Pipeline"

         - name: Step 2 - Show files in repo
           run: ls -la

         - name: Step 3 - Show working directory
           run:  pwd

         - name: Step 4 - Show system info
           run: uname -a

         - name: Step5 - Show current date  
           run: date